Upduino.v
../rtl/cpu/hazard2_cpu.v 
../rtl/cpu/Hazard2.v 
../rtl/SoC/Hazard2_SoC.v 
../rtl/SoC/ahbl_splitter_4.v 
../rtl/memory/ahbl_ram.v 
../rtl/memory/ahbl_rom.v 
../rtl/gpio/ahbl_gpio.v
../rtl/gpio/ahbl_gpio_splitter.v
../rtl/uart/ahbl_uart.v
../rtl/uart/uart_tx.v
../rtl/uart/serial_terminal.v
../rtl/timer/ahbl_counter.v
../rtl/timer/counter.v
../rtl/timer/prescaler_counter.v
../rtl/accelerator/multiplier.v
../rtl/accelerator/ahbl_mult.v
