Upduino.v
../cpu/hazard2_cpu.v 
../cpu/Hazard2.v 
../SoC/Hazard2_SoC.v 
../SoC/ahbl_splitter_4.v 
../memory/ahbl_ram.v 
../memory/ahbl_rom.v 
../gpio/ahbl_gpio.v
../gpio/ahbl_gpio_splitter.v
../uart/ahbl_uart.v
../uart/uart_tx.v
../uart/serial_terminal.v
../timer/ahbl_counter.v
../timer/counter.v
../timer/prescaler_counter.v
